add attack_utilities and more tests
AI-SDC/SACRO-ML pull request #20
Opened 2022-08-03 16:16 UTC by rpreen

2022-08-09 07:43 UTC, simonrnss requested changes
A couple of suggestions -- not sure why we need the attack_utilities code? Where is it being imported?

2022-08-09 07:43 UTC, simonrnss commented on attack_utilities/estimator_template.py
> +'''
I think this probably needs better commenting / docs.
Do we actually use it though? I thought these classes had been superseded by the safe wrappers?

2022-08-09 07:43 UTC, simonrnss commented on attack_utilities/dp_svc_example.py
> +'''
Not sure we need this code? And if we do, it would find a more natural home in the examples folder?

2022-08-09 07:50 UTC, simonrnss commented
@rpreen please also check pylint output -- if you're happy to overrule its variable name issues then adding
```python
# pylint: disable = invalid-name
```
to the offending files will shut pylint up. It's also finding near duplicate code in the test files. This might be unavoidable.

2022-08-12 13:08 UTC, rpreen commented
Yeah, the `attack_utilities` should be removed if it's not needed. I think the pylint clean up should be a new issue/PR though since most of the complaints are about the safe model modules which aren't really dealt with in this PR (this is about adding tests)

2022-08-12 13:14 UTC, mccarthyajb commented
OK, to be clear that's removing the entire attack_utilities directory? 
I don't think safesvc references it anymore.

2022-08-12 13:28 UTC, rpreen commented
yes

2022-08-12 14:05 UTC, mccarthyajb commented
OK, we were still importing GenericEstimator and the DPSVC class was inheriting it. 
I've removed those dependencies and the attack_utilities directory. The test are successful without them.

2022-08-12 14:17 UTC, merged